name: Ask a question
description: Ask a question about rex
labels: [question,needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question about rex, that is not a bug report or a feature request, you can ask it here. For more real-time help with rex, from us and the community, join our [Slack](https://angr.io/invite/).

        Before submitting this question, please check the following, which may answer your question:
        * Have you checked the [documentation](https://docs.angr.io/)?
        * Have you checked the [FAQ](https://docs.angr.io/introductory-errata/faq)?
        * Have you checked our library of [examples](https://github.com/angr/angr-doc/tree/master/examples)?
        * Have you [searched existing issues](https://github.com/angr/rex/issues?q=is%3Aissue+label%3Aquestion) to see if this question has been answered before?
        * Have you checked that you are running the latest versions of angr and its components. angr is rapidly-evolving!

        **Please note: This repo is effectively unmaintained. While we appreciate bug reports and feature requests, we cannot commit to a timely response.** For more real-time help with angr, from us and the community, join our [Slack](https://angr.io/invite/).

  - type: textarea
    attributes:
      label: Question
      description:
    validations:
      required: true
